### ISSUE TITLE
bnx2 - Broadcom Limited NetXtreme II BCM5709 Gigabit Ethernet (rev 20)

### ISSUE THREAD

**Issue by jpoliv** [isc-projects/ethq#14]
NIC: Broadcom Limited NetXtreme II BCM5709 Gigabit Ethernet (rev 20)
Driver: bnx2

$ ethtool -i eth0
driver: bnx2
version: 2.2.6
firmware-version: bc 5.2.3 NCSI 2.0.12
expansion-rom-version:
bus-info: 0000:03:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: no

$ ethtool -S eth0
NIC statistics:
     rx_bytes: 12532335371359
     rx_error_bytes: 0
     tx_bytes: 48799173902667
     tx_error_bytes: 0
     rx_ucast_packets: 19363870912
     rx_mcast_packets: 4826228
     rx_bcast_packets: 38192715
     tx_ucast_packets: 41213192818
     tx_mcast_packets: 442756
     tx_bcast_packets: 101
     tx_mac_errors: 0
     tx_carrier_errors: 0
     rx_crc_errors: 0
     rx_align_errors: 0
     tx_single_collisions: 0
     tx_multi_collisions: 0
     tx_deferred: 0
     tx_excess_collisions: 0
     tx_late_collisions: 0
     tx_total_collisions: 0
     rx_fragments: 0
     rx_jabbers: 0
     rx_undersize_packets: 0
     rx_oversize_packets: 0
     rx_64_byte_packets: 47903542
     rx_65_to_127_byte_packets: 213204013
     rx_128_to_255_byte_packets: 1496176960
     rx_256_to_511_byte_packets: 807022245
     rx_512_to_1023_byte_packets: 674619050
     rx_1024_to_1522_byte_packets: 3283062157
     rx_1523_to_9022_byte_packets: 0
     tx_64_byte_packets: 7144408
     tx_65_to_127_byte_packets: 289112807
     tx_128_to_255_byte_packets: 2252555245
     tx_256_to_511_byte_packets: 1927965455
     tx_512_to_1023_byte_packets: 1593313487
     tx_1024_to_1522_byte_packets: 783806543
     tx_1523_to_9022_byte_packets: 0
     rx_xon_frames: 0
     rx_xoff_frames: 0
     tx_xon_frames: 306
     tx_xoff_frames: 332
     rx_mac_ctrl_frames: 0
     rx_filtered_packets: 20991495
     rx_ftq_discards: 0
     rx_discards: 0
     rx_fw_discards: 0

**Comment by raybellis** [comment]
Thanks for the info - support added in commit 35b9de3f3811727950e19dc8441e89ac001debc2
