### ISSUE TITLE
Does this tool support milliseconds level data?

### ISSUE THREAD

**Issue by Jeffwan** [isc-projects/ethq#17]
I need to monitor milliseconds level metrics. I am wondering if this has support?

**Comment by raybellis** [comment]
Can you elaborate on your use case?   The tool *could* monitor more rapidly, but in UI mode you'd never be able to see the screen updates.

**Comment by raybellis** [comment]
I don't propose to support this directly, but you could modify the `time_wait` function to add e.g. 50ms at a time to `now` (not forgetting to increment `.tv_sec` if the `.tv_nsec` field wraps through 1e9).

You would also have to modify the calculation of `bps` in the `out_data()` function to convert back into "per second" values.

**Comment by Jeffwan** [comment]
@raybellis  Many thanks! BTW, if I use very short interval like 1ms or 5ms. Is the result precise?

**Comment by raybellis** [comment]
No, it won't be very precise - it'll depend on how long it takes the O/S to return the driver statistics and for my code to retrieve them and process them.    Either way, you should use the text mode and output to a file - trying to view them in real-time would be futile.

**Comment by Jeffwan** [comment]
Thanks for the tips. I will.
