### ISSUE TITLE
support for sfc driver

### ISSUE THREAD

**Issue by dsahern** [isc-projects/ethq#19]
ethtool data for sfc driver is given below. This is from top of net-next tree (5.7), commit:
    6545be82807c ("sfc: fix dereference of table before it is null checked")

This works for me:
static RegexParser solarflare_sfc(
	{ "sfc" },
        RegexParser::total_nomatch,
        { "^(rx|tx)-(\\d+)\\.rx_(bytes|packets)$", { 1, 3, 2 } }
);

$ ethtool -i eth0
driver: sfc
version: 4.1
firmware-version: 6.2.7.1000 rx0 tx0
expansion-rom-version:
bus-info: 0000:82:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: no
supports-register-dump: yes
supports-priv-flags: no
dahern@s2r5node42:~$ ethtool -S eth0
NIC statistics:
     rx_noskb_drops: 0
     rx_nodesc_trunc: 0
     port_tx_bytes: 795279
     port_tx_packets: 1865
     port_tx_pause: 0
     port_tx_control: 0
     port_tx_unicast: 1799
     port_tx_multicast: 66
     port_tx_broadcast: 0
     port_tx_lt64: 0
     port_tx_64: 58
     port_tx_65_to_127: 1084
     port_tx_128_to_255: 145
     port_tx_256_to_511: 109
     port_tx_512_to_1023: 92
     port_tx_1024_to_15xx: 67
     port_tx_15xx_to_jumbo: 310
     port_rx_bytes: 410901
     port_rx_good_bytes: 410901
     port_rx_bad_bytes: 0
     port_rx_packets: 1653
     port_rx_good: 1653
     port_rx_bad: 0
     port_rx_pause: 0
     port_rx_control: 0
     port_rx_unicast: 1147
     port_rx_multicast: 474
     port_rx_broadcast: 32
     port_rx_lt64: 0
     port_rx_64: 60
     port_rx_65_to_127: 1039
     port_rx_128_to_255: 298
     port_rx_256_to_511: 71
     port_rx_512_to_1023: 38
     port_rx_1024_to_15xx: 147
     port_rx_15xx_to_jumbo: 0
     port_rx_gtjumbo: 0
     port_rx_bad_gtjumbo: 0
     port_rx_overflow: 0
     port_rx_nodesc_drops: 0
     port_rx_pm_trunc_bb_overflow: 0
     port_rx_pm_discard_bb_overflow: 0
     port_rx_pm_trunc_vfifo_full: 0
     port_rx_pm_discard_vfifo_full: 0
     port_rx_pm_trunc_qbb: 0
     port_rx_pm_discard_qbb: 0
     port_rx_pm_discard_mapping: 0
     port_rx_dp_q_disabled_packets: 0
     port_rx_dp_di_dropped_packets: 27
     port_rx_dp_streaming_packets: 0
     port_rx_dp_hlb_fetch: 0
     port_rx_dp_hlb_wait: 0
     rx_unicast: 1146
     rx_unicast_bytes: 361894
     rx_multicast: 390
     rx_multicast_bytes: 35635
     rx_broadcast: 32
     rx_broadcast_bytes: 2052
     rx_bad: 0
     rx_bad_bytes: 0
     rx_overflow: 0
     tx_unicast: 1799
     tx_unicast_bytes: 787362
     tx_multicast: 60
     tx_multicast_bytes: 7457
     tx_broadcast: 0
     tx_broadcast_bytes: 0
     tx_bad: 0
     tx_bad_bytes: 0
     tx_overflow: 0
     tx_merge_events: 3
     tx_tso_bursts: 82
     tx_tso_long_headers: 0
     tx_tso_packets: 390
     tx_tso_fallbacks: 0
     tx_pushes: 1231
     tx_pio_packets: 1247
     tx_cb_packets: 2
     rx_reset: 0
     rx_tobe_disc: 0
     rx_ip_hdr_chksum_err: 0
     rx_tcp_udp_chksum_err: 0
     rx_inner_ip_hdr_chksum_err: 0
     rx_inner_tcp_udp_chksum_err: 0
     rx_outer_ip_hdr_chksum_err: 0
     rx_outer_tcp_udp_chksum_err: 0
     rx_eth_crc_err: 0
     rx_mcast_mismatch: 0
     rx_frm_trunc: 0
     rx_merge_events: 0
     rx_merge_packets: 0
     rx_xdp_drops: 0
     rx_xdp_bad_drops: 0
     rx_xdp_tx: 0
     rx_xdp_redirect: 0
     rfs_filter_count: 0
     rfs_succeeded: 0
     rfs_failed: 0
     tx-0.tx_packets: 130
     tx-1.tx_packets: 339
     tx-2.tx_packets: 129
     tx-3.tx_packets: 62
     tx-4.tx_packets: 97
     tx-5.tx_packets: 39
     tx-6.tx_packets: 171
     tx-7.tx_packets: 111
     tx-8.tx_packets: 53
     tx-9.tx_packets: 92
     tx-10.tx_packets: 218
     tx-11.tx_packets: 439
     tx-12.tx_packets: 0
     tx-13.tx_packets: 0
     tx-14.tx_packets: 0
     tx-15.tx_packets: 0
     tx-16.tx_packets: 0
     tx-17.tx_packets: 0
     rx-0.rx_packets: 232
     rx-1.rx_packets: 115
     rx-2.rx_packets: 86
     rx-3.rx_packets: 130
     rx-4.rx_packets: 225
     rx-5.rx_packets: 86
     rx-6.rx_packets: 179
     rx-7.rx_packets: 139
     rx-8.rx_packets: 169
     rx-9.rx_packets: 114
     rx-10.rx_packets: 50
     rx-11.rx_packets: 60
     tx-xdp-cpu-0.tx_packets: 0
     tx-xdp-cpu-1.tx_packets: 0
     tx-xdp-cpu-2.tx_packets: 0
     tx-xdp-cpu-3.tx_packets: 0
     tx-xdp-cpu-4.tx_packets: 0
     tx-xdp-cpu-5.tx_packets: 0
     tx-xdp-cpu-6.tx_packets: 0
     tx-xdp-cpu-7.tx_packets: 0
     tx-xdp-cpu-8.tx_packets: 0
     tx-xdp-cpu-9.tx_packets: 0
     tx-xdp-cpu-10.tx_packets: 0
     tx-xdp-cpu-11.tx_packets: 0
     tx-xdp-cpu-12.tx_packets: 0
     tx-xdp-cpu-13.tx_packets: 0
     tx-xdp-cpu-14.tx_packets: 0
     tx-xdp-cpu-15.tx_packets: 0
     tx-xdp-cpu-16.tx_packets: 0
     tx-xdp-cpu-17.tx_packets: 0
     tx-xdp-cpu-18.tx_packets: 0
     tx-xdp-cpu-19.tx_packets: 0
     tx-xdp-cpu-20.tx_packets: 0
     tx-xdp-cpu-21.tx_packets: 0
     tx-xdp-cpu-22.tx_packets: 0
     tx-xdp-cpu-23.tx_packets: 0

**Comment by raybellis** [comment]
This looks straight forward enough, but given there's no per-queue RX bytes figure we should derive a regex to at least report on the total RX bytes.

**Comment by raybellis** [comment]
With apologies for the delay, this is now added with commit a8e3ad8549e82fe91a33ac897fbc5b28a0f734d3

I've added total rx/tx byte and packet counters, and also fixed the RegEx so that it also matches TX queues.
