### ISSUE TITLE
The tool doesn't work on EL7.5 (gcc 4.8.5)

### ISSUE THREAD

**Issue by vstax** [isc-projects/ethq#2]
The tool gives "regex_error" on EL 7.5 (gcc-4.8.5-28.el7_5.1.x86_64, libstdc++-4.8.5-28.el7_5.1.x86_64). This is for Intel X540-AT2 card, though the error happens during regex initialization in build_queue_map():
```
# ./ethq eth3
error: regex_error
```
The reason being C++11 RE supported only in gcc 4.9 or higher. So to support these (pretty popular) platforms, pcre or another library should be used instead of relying on C++/stdc++ regex support.

**Comment by raybellis** [comment]
The whole code depends on C++11 support (e.g. the `auto` keyword).

I understand that RH do also make later GCC binaries available?

**Comment by vstax** [comment]
C++11 is supported by gcc 4.8.5, including auto keyword and everything. But regex support is flaky in gcc in general. E.g. gcc 4.9 has better regex support, but still has various problems with regex and doesn't support some regular expressions. Gcc 5.3 is buggy as well: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70411
And even in latest version of gcc/libstdc++ has some serious bugs like https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61582 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61601

You can install later versions of GCC but it's pretty complicated (need dev collections repo, and that gcc won't be main compiler and harder to use), it's best to assume that it's just not available. It's possible to install clang (3.4.2), however. I've installed it and compiled the code, but the error is the same. My guess is that problem is in libstdc++. I've tried compiling with clang and linking with libc++ instead but it doesn't work because code uses exceptions, and workarounds like https://stackoverflow.com/a/30527424 don't work because, once again, with older gcc libc++abi and libsupc++ aren't available.

I think the simplest solution is to use boost for regex (yes, pretty heavyweight dependency but still) or C-style pcre.

**Comment by raybellis** [comment]
I'm certainly not going to bring in Boost as a dependency (I'm highly allergic to it) but I'll look into pcre.
