### ISSUE TITLE
'std::regex_error' exception due to old gcc-c++ compiler

### ISSUE THREAD

**Issue by jpoliv** [isc-projects/ethq#5]
The following exception is thrown by ethq compiled with the CentOS 7 standard C++ compiler:

$ ./ethq -h
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted

$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)

Platforms affected:
RHEL 7 / CentOS 7 (and most likely either linux distros where gcc version < 4.9) 

Workaround:
Use a more recent C++ compiler (like gcc v6 or v7) from the RH software collections.

References:
 * terminate called after throwing an instance of 'std::regex_error'
   https://stackoverflow.com/questions/37411117/terminate-called-after-throwing-an-instance-of-stdregex-error

 * Software Collections
   https://www.softwarecollections.org

   Developer Toolset 6
   https://www.softwarecollections.org/en/scls/rhscl/devtoolset-6/

   Developer Toolset 7
   https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/

 * Software Collections SIG
   https://wiki.centos.org/SpecialInterestGroup/SCLo

**Comment by jpoliv** [comment]
This is a duplicate of issue #2 .

Note: ethq worked as expected when compiled with gcc-c++ from devtoolset-6.

**Comment by raybellis** [comment]
Thanks for the links to working compilers for RHEL :)
