### ISSUE TITLE
Show '-' instead of zero for missing counters

### ISSUE THREAD

**Issue by raybellis** [isc-projects/ethq#9]
Some drivers don't include all of the necessary counters.

**Comment by raybellis** [comment]
@sleinen could you please try 587ceb39c2af5fc617cae37319ff6d97cc9e5a99 to see if it correctly shows a `-` instead of `0` for missing stats values?

**Comment by raybellis** [comment]
resolved with c9a05cd8ab33e7a6a2bfe5b97effc1dae2dbcc7b

**Comment by sleinen** [comment]
I would have loved to test this, but the Linux kernels on my servers have been upgraded, and the missing values (per-tx/rx-queue byte counters) are now present.  See my last comments on #8.
